### ISSUE TITLE
Janggi errors

### ISSUE THREAD

**Issue by cab101** [fairy-stockfish/Fairy-Stockfish#610]
Originally **pass_on_stalemate**() was used for janggi.
https://github.com/fairy-stockfish/Fairy-Stockfish/commit/7952fae1a9a59d7168f5ca8340ebbdd9b40d1276#diff-2a523082b4e3a1ee6185d1d1fc07c2ad9199c5069453917a860c1cd94c8f34e4R350
https://github.com/fairy-stockfish/Fairy-Stockfish/commit/7952fae1a9a59d7168f5ca8340ebbdd9b40d1276#diff-1d066214056be2b8958a2a2143c121d339937f753cdd7b5361cf1cece354480dR877

but now
https://github.com/fairy-stockfish/Fairy-Stockfish/blob/master/src/position.cpp#L1070 use it
https://github.com/fairy-stockfish/Fairy-Stockfish/blob/master/src/movegen.cpp#L446 use pass()

May be **pass_on_stalemate**() is obsolete?

**Comment by ianfab** [comment]
I am not sure I understand what you mean. If you think there is a bug, please specify exact commands how to reproduce it. And if there is a working feature you don't need, just ignore it.

**Comment by cab101** [comment]
_uci
setoption name UCI_Variant value janggi
position startpos moves e2e2 e9e9
go_

debug
_Fen: rnba1abnr/4k4/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/4K4/RNBA1ABNR w - - 2 2_

Both e2e2 and e9e9 (use for pass) are illegal.
Replacing **pass_on_stalemate**() -> **pass**() in position.cpp fix it.

Also, could you tell me when the release will be?

**Comment by ianfab** [comment]
Thanks for the example. I don't exactly understand the problem though, as both passing moves are legal and Fairy-SF correctly handles that, and after the two passing moves the game is over and is adjudicated by point scoring. So from my perspective everything there is working as expected. If your point is that in your opinion the rule implementation should be different, that is nothing that I can address, since this ruleset is the consensus regarding janggi tournament rules we arrived at after long discussion with many people, including pro players, and this ruleset is stable in Fairy-SF for several years now, so it would require an extraordinary level of evidence to the contrary to change this.
