### ISSUE TITLE
Add "Piece in flag zone is not victory if it can be captured next move" option

### ISSUE THREAD

**Issue by RainRat** [fairy-stockfish/Fairy-Stockfish#664]
For Alapo and others. Can be simulated with promotion, as seen in variants.ini, but is not elegant.

**Comment by ianfab** [comment]
Usually flagMove was sufficient to cover this, e.g., in jeson mor. Are there scenarios where this can not be used?

**Comment by RainRat** [comment]
It's close, but it's not quite the same. In Alapo, if you move into the flag zone, and the piece can't be captured immediately, the game should be adjudicated in your favor immediately.

**Comment by ianfab** [comment]
I see. Currently two concepts are a bit mixed under the flagMove, namely whether you are allowed to continue the game by capturing the piece, and whether you are able to draw by reaching the flagRegion yourself on the very next move.

Perhaps it would make sense to separate these concepts and make it cleaner and to be able to support what you are suggesting. So far there just was no strong need for that because the variants so far happen to work with the current limited configurability, e.g., for Jeson Mor simply because there only is one target square, so capturing and reaching your own target region always co-occur.

**Comment by RainRat** [comment]
Solved in #719
