### ISSUE TITLE
How to embed a variant in PlayStrategy?

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [fairy-stockfish/Fairy-Stockfish#671]
(Particularly Nighty Zones and Faceoff, I write that here to get you notified)

**Comment by gbtami** [comment]
Why don't you ask it on https://github.com/mind-sports-games/lila ?

**Comment by Rechefiltr-is-Fire** [comment]
I’ve notified Statmatt who said 

> Your best hope is to get this variant into the FairyStockfish project: [github.com/fairy-stockfish/Fairy-Stockfish](https://github.com/fairy-stockfish/Fairy-Stockfish)
If you can do that, then it makes the job of adding it to PlayStrategy much easier and it would bring a high quality AI to play against/analyse games.

Imported from PlayStrategy PM.

⚡ ❓

**Comment by ianfab** [comment]
There are two different levels of "supported" variants in Fairy-SF:
* Built-in variants
* Variants that can be configured using variants.ini

Built-in variants generally are the easiest to handle for projects using Fairy-SF, but configurable variants should usually also not be a problem as you can e.g. see in use on pychess.

I generally won't accept newly invented variants as built-in variants unless there are very good reasons to do so, because built-in variants should be well established games. And for variants that are supported via configuration there is no need for code changes as everyone can define their own INI.

So only if playstrategy
1. has serious plans to add a specific variant AND
2. does not want to support variants via INI configuration

then it could at least be considered to add such a new variant to the built-in ones, but I doubt that will happen (as they also focus on relevant variants) and generally would not be much in favor of it.
