### ISSUE TITLE
Make All the Variants Defined in a .ini File instead of Other Types of Files

### ISSUE THREAD

**Issue by PraseodymiumSpike** [fairy-stockfish/Fairy-Stockfish#700]
It's annoying when I am trying to make a variant that inherits from an existing variant, but that existing variant is in a .cpp file like [this](https://github.com/fairy-stockfish/Fairy-Stockfish/blob/master/src/variant.cpp), and it has different syntax to the .ini files, and I'm not sure exactly which rules are going to be inherited. I have to then define it from scratch or just try to figure out what the .cpp file means. It would be better if everything was just in .ini files. Also, it makes it easier to make pull requests for people who are familiar with the .ini syntax for this.

**Comment by ianfab** [comment]
I see the value of this proposal, but currently I don't think it is realistic to expect that this will happen. It might not always be possible or practical to expose everything that is possible via the code to be available via the INI, and at the same time there also is the significant difference that built-in variants are available always and guaranteed, while variants from the INI are loaded at runtime, so they require an additional file and might or might not be available.

Therefore, to me this would only be an option if there was a mechanism to include an INI at build time, so that a given set of variant can be guaranteed to be supported. Since I think this is unlikely to be the case, the more likely alternative seems to me to support generation of an INI file from built-in variants. This would perhaps also address your use-case and be a less invasive change. It would still be a quite big change to implement such an INI generation though, so it is unlikely to happen any time soon.
