### ISSUE TITLE
Update Fairy-Stockfish wiki

### ISSUE THREAD

**Issue by Kei-Toba** [fairy-stockfish/Fairy-Stockfish#829]
I’ve noticed several dead links in the Fairy-Stockfish Wiki that need to be replaced with appropriate ones. One such link is: [Setting up Fairy-Stockfish on FICS for Linux](https://github.com/fairy-stockfish/Fairy-Stockfish/wiki/Setting-up-Fairy-Stockfish-on-FICS#linux).

Additionally, it would be beneficial to create a cheat sheet or include external links regarding the extended FEN format used in Fairy-Stockfish, especially for non-developers. By examining `variants.ini`, you will notice several symbols not found in Standard FEN, such as `[-], 3+3, and K*`. I’ve also discovered the use of `\` in the FEN within the Fairy-Stockfish source code.

I am exploring the possibility of adapting Chess960 to Shogi, and I'm curious about how the Chess960 starting positions are represented in FEN—specifically, whether X-FEN is being utilized.

I have created rules for unlisted variants, and I would like to analyze these variants using a GUI. However, I require Xboard for this, but unfortunately, the link to Xboard on the Fairy-Stockfish Wiki is broken. Additionally, building the GNU Project's Xboard tarball results in errors, and even if I successfully build it, Xboard may crash due to `error: broken pipe`.

I believe the best solution would be to use an AppImage for Xboard, but there doesn’t seem to be one available at this time.

I recognize that this issue may be inappropriate for the Fairy-Stockfish project, and I may be making overly ambitious requests. However, I feel I am currently lacking the necessary expertise to address these issues myself, so I am relying on your development team. Thank you.

**Comment by yjf2002ghty** [comment]
>  By examining variants.ini, you will notice several symbols not found in Standard FEN, such as `[-], 3+3, and K*`. I’ve also discovered the use of `\` in the FEN within the Fairy-Stockfish source code.

**`[-]`**: This is equivalent to `[]`, which means there is no piece in both players' pockets.
**`3+3`**: This is used in variants that counts the number of checks, such as `3check`. 3+3 means both players have 3 remaining checks. Once checked by the opponent, the number decreases by 1. If the number is 0 and the player is checked, that player loses. For those variants that do not count the number of checks, this part is omitted.
**`K*`**: The character `*` means a wall square, which is a piece that cannot be moved and captured by both player. This is used to represent unreachable squares, such as boards with holes or non-rectangular boards.



> I am exploring the possibility of adapting Chess960 to Shogi, and I'm curious about how the Chess960 starting positions are represented in FEN—specifically, whether X-FEN is being utilized.

The only thing that changes in Fischer random variants is the notation of castling rights in the FEN. For standard variants, `KQkq` 
is the format while in 960 variants, `AHah` is the format. In 960 variants, castling notation uses the file where the rooks are initially. For example, in this position:
![image](https://github.com/user-attachments/assets/17028b84-9b4c-4501-964a-d438f41ae340)
The FEN is `brnqkbnr/pppppppp/8/8/8/8/PPPPPPPP/BRNQKBNR w HBhb - 0 1`, because the rooks are at b-file and h-file.



> I have created rules for unlisted variants, and I would like to analyze these variants using a GUI. However, I require Xboard for this, but unfortunately, the link to Xboard on the Fairy-Stockfish Wiki is broken. Additionally, building the GNU Project's Xboard tarball results in errors, and even if I successfully build it, Xboard may crash due to error: broken pipe.

Visit [https://github.com/fairy-stockfish/Fairy-Stockfish/wiki/Graphical-user-interfaces](https://github.com/fairy-stockfish/Fairy-Stockfish/wiki/Graphical-user-interfaces) to see the available GUIs for Fairy-Stockfish (FSF).

**Comment by ianfab** [comment]
> I’ve noticed several dead links in the Fairy-Stockfish Wiki that need to be replaced with appropriate ones. One such link is: [Setting up Fairy-Stockfish on FICS for Linux](https://github.com/fairy-stockfish/Fairy-Stockfish/wiki/Setting-up-Fairy-Stockfish-on-FICS#linux).

If there are obvious mistakes in the wiki, you are invited to fix them yourself, it is a wiki intentionally. If you want to do bigger changes it is good practice to discuss it first (e.g., on discord) to align, but obvious minor corrections can of course be done without question. Improvement of documentation generally is a continuous and collective process, so please don't expect too many major short term changes.

> Additionally, it would be beneficial to create a cheat sheet or include external links regarding the extended FEN format used in Fairy-Stockfish, especially for non-developers. By examining `variants.ini`, you will notice several symbols not found in Standard FEN, such as `[-], 3+3, and K*`. I’ve also discovered the use of `\` in the FEN within the Fairy-Stockfish source code.

There is https://fairy-stockfish.github.io/chess-variant-standards/ and more specifically https://fairy-stockfish.github.io/chess-variant-standards/fen.html that tries to collect variant extensions for chess standards. It could maybe be referred

> I am exploring the possibility of adapting Chess960 to Shogi, and I'm curious about how the Chess960 starting positions are represented in FEN—specifically, whether X-FEN is being utilized.

For variants without castling from the engine perspective randomization does not really matter, it is just like any custom position.

> I have created rules for unlisted variants, and I would like to analyze these variants using a GUI. However, I require Xboard for this, but unfortunately, the link to Xboard on the Fairy-Stockfish Wiki is broken. Additionally, building the GNU Project's Xboard tarball results in errors, and even if I successfully build it, Xboard may crash due to `error: broken pipe`.
> 
> I believe the best solution would be to use an AppImage for Xboard, but there doesn’t seem to be one available at this time.
> 
> I recognize that this issue may be inappropriate for the Fairy-Stockfish project, and I may be making overly ambitious requests. However, I feel I am currently lacking the necessary expertise to address these issues myself, so I am relying on your development team. Thank you.

The WinBoard download link is working for some, there just seem to be issues depending on internet provider or something like that where this somehow seems blocked. But a hint to this problem next to the link could be useful. Honestly, the lack of application stability and hard to reproduce build process for Winboard/XBoard does not encourage me much to use it, but I still try to document as good as I can despite that.
